#!/bin/bash -e

set -x

cd /tmp/packages
tar -C /tmp -xf libddwaf-*.tar.gz --strip-components=2 `tar -tf libddwaf-*.tar.gz | grep /libddwaf.so`

docker run --rm -i --platform aarch64 -v /tmp/packages/smoketest/gnu_static-smoketest:/usr/local/bin/smoketest \
	ubuntu@sha256:11c7a73a8eb322a177481fdeafc34957200f2f0d1f2192044ad5262008d4bba9 \
	smoketest
docker run --rm -i --platform aarch64 -v /tmp/packages/smoketest/gnu_shared-smoketest:/usr/local/bin/smoketest \
	-v /tmp/libddwaf.so:/usr/local/lib/libddwaf.so \
  -e LD_LIBRARY_PATH=/usr/local/lib \
	ubuntu@sha256:11c7a73a8eb322a177481fdeafc34957200f2f0d1f2192044ad5262008d4bba9 \
  smoketest

docker run --rm -i --platform aarch64 -v /tmp/packages/smoketest/musl_static_libgcc-smoketest:/usr/local/bin/smoketest \
  alpine@sha256:17d432b0c16d46b7d978dd82a14084f7bcebe497532baea3e3cd9864eb044406 \
  smoketest

docker run --rm -i --platform aarch64 -v /tmp/packages/smoketest/musl_static_llvm-smoketest:/usr/local/bin/smoketest \
  alpine@sha256:17d432b0c16d46b7d978dd82a14084f7bcebe497532baea3e3cd9864eb044406 \
  smoketest

docker run --rm -i --platform aarch64 -v /tmp/packages/smoketest/musl_shared-smoketest:/usr/local/bin/smoketest \
	-v /tmp/libddwaf.so:/usr/local/lib/libddwaf.so \
  alpine@sha256:17d432b0c16d46b7d978dd82a14084f7bcebe497532baea3e3cd9864eb044406 \
  smoketest

rm -rf /tmp/packages/smoketest
