name: Benchmark

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt-get -y update 
          sudo apt-get -y upgrade
          DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install python3 apt-transport-https build-essential wget cmake git

      - name: Build
        run: |
            set -ex
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            VERBOSE=1 make -j benchmark benchcmp

      - name: Run Benchmark
        run: |
            cd build
            make run_benchmark

      - name: Download previous run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: benchmark.yml
          workflow_conclusion: success
          name: benchmark-data
          path: previous
          branch: master
        continue-on-error: true

      - name: Compare performance
        run: |
            ./build/perf/benchcmp previous/benchmark_results.json benchmark_results.json
        continue-on-error: true

      - name: Artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: benchmark-data
          path: benchmark_results.json
