name: Fuzz

on:
  # schedule:
  #   - cron:  30 0 * * *
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration of the fuzzing run in seconds'
        required: true
        default: "60"
        type: string


jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt-get -y update 
          sudo apt-get -y upgrade
          DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install python3 apt-transport-https build-essential wget cmake git clang-14 libfuzzer-14-dev

      - name: Build
        run: ./fuzzing/build.sh

      - name: Run fuzzer
        run: ./fuzzing/run.sh ${{ github.event.inputs.duration }}

      - name: Log
        if: ${{ always() }}
        run: grep -v -f fuzzing/scripts/report-negative-patterns.txt fuzzing/fuzz-*.log

      - name: Show coverage
        run: ./fuzzing/scripts/show_coverage.sh 40

      - name: Compress artifact
        if: ${{ always() }}
        run: tar -czvf fuzzing.tar.gz fuzzing/

      - name: Artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: fuzzing-data
          path: fuzzing.tar.gz
