name: Validate

on:
  push:
    branches: [ master ]
    tags:
      - "*"
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  30 0 * * *
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build WAF
        env:
          CC: gcc-9
          CXX: g++-9
        run: |
          set -ex
          mkdir Debug && cd Debug
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="-fsanitize=address,leak,undefined -DASAN_BUILD" \
            -DCMAKE_C_FLAGS="-fsanitize=address,leak,undefined -DASAN_BUILD" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,leak,undefined" \
            -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address,leak,undefined"
          VERBOSE=1 make -j waf_validator
      - name: Run Validator
        run: |
          set -ex
          cd Debug
          make validate
